name: shoes_store
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.1 <4.0.0'

#---------------------------- Packages ----------------------------#
dependencies:
  flutter:
    sdk: flutter

# Utility packages
  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6

  # Product Specific

#---------------------------- ./Packages End ----------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#------------------------- Local Assets-------------------------#
  assets:
    - assets/

#------------------------- Local Fonts -------------------------#
  fonts:
    - family: Poppins
      fonts:
       - asset: assets/font/Poppins-Regular.ttf
         weight: 400
       - asset: assets/font/Poppins-Medium.ttf
         weight: 500
       - asset: assets/font/Poppins-Bold.ttf
         weight: 800
       - asset: assets/font/Poppins-Italic.ttf
         style: italic
       - asset: assets/font/Poppins-SemiBold.ttf
         weight: 600
       - asset: assets/font/Poppins-MediumItalic.ttf
         weight: 500
       - asset: assets/font/Poppins-Regular.ttf
         weight: 400
       - asset: assets/font/Poppins-Regular.ttf
         weight: 400
